name: CI/CD
on: [push]

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: CI=true npm ci
      # - name: Code Climate - Setup
      #   # Install the Code Climate reporter in workspace
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build
      - name: Test
        run: npm test
      # - name: Code Climate - Report
      #   if: success()
      #   # Upload test code coverage report to Code Climate (branch must be explicitly set)
      #   run: |
      #     export GIT_BRANCH="${GIT_BRANCH:-${GITHUB_REF:11}}"
      #     ./cc-test-reporter after-build
      #   env:
      #     GIT_BRANCH: ${{ github.head_ref }}
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
